# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e70400b0f4e4dc4177844f18e5746c3"
name = "Loyalty Point"
application_url = "https://mechanism-diagnostic-floppy-losses.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-webential-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_inventory,write_inventory,read_customers,write_customers,customer_read_customers,customer_write_customers,customer_read_orders,customer_read_draft_orders"

[auth]
redirect_urls = [
  "https://mechanism-diagnostic-floppy-losses.trycloudflare.com/auth/callback",
  "https://mechanism-diagnostic-floppy-losses.trycloudflare.com/auth/shopify/callback",
  "https://mechanism-diagnostic-floppy-losses.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
