# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e70400b0f4e4dc4177844f18e5746c3"
name = "my-app"
application_url = "https://lodge-stockings-behavior-spending.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-webential-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_inventory,write_inventory,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://lodge-stockings-behavior-spending.trycloudflare.com/auth/callback",
  "https://lodge-stockings-behavior-spending.trycloudflare.com/auth/shopify/callback",
  "https://lodge-stockings-behavior-spending.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
